### ISSUE TITLE
Wrinting Text 

### ISSUE THREAD

**Issue by sebbi08** [screepers/screeps-visual#3]
When i try to write some tex with the folowing code:

```
let visual = new Visual(room.name);

visual.font = '1px Arial';
visual.fillStyle = "black";
visual.textAlign = "left";
visual.fillText(text1, 38, 28);
visual.fillText(text2, 38, 29);
visual.fillText(text3, 38, 30);
visual.fillText(text4, 38, 31);

visual.commit();
```

i only get som meshed up letters

**Comment by AlinaNova21** [comment]
Thats because 1px is VERY tiny, try a larger number. ;)

**Comment by sebbi08** [comment]
tryed but 1px is execly one square in the game world and using higher nubers gets me masiv letters :)

im using the steam client btw.

1px:
![1px](https://cloud.githubusercontent.com/assets/9070136/25090012/4e2e7b52-2381-11e7-9c42-b4fc7333e2b7.PNG)
20px:
![20px](https://cloud.githubusercontent.com/assets/9070136/25090013/4e30342e-2381-11e7-821c-e5b9110fc3e4.PNG)

**Comment by AlinaNova21** [comment]
Hmm, I thought it was working before, I don't actually use this anymore since the builtin visuals work better and easier in most cases.
